name: B

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: 检出仓库
      uses: actions/checkout@v4

    - name: 设置Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: 安装 GitHub CLI
      uses: actions/setup-gh@v3
      with:
        version: 'latest'
    
    - name: 使用 PAT 登录
      env:
        GH_TOKEN: ${{ secrets.PAT }}
      run: |
        gh auth setup-git
        gh auth status


    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 运行
      run: python b.py